#!/bin/bash

#
# ${HCP_RUN_UTILS}/lib/ccf/multirunicafix_processing/one_subject_completion_checker
# Script to run structural preprocessing one subject completion checker Python code
# Copyright 2019, The Connectome Coordination Facility
#

if [ -z "${HCP_RUN_UTILS}" ]; then
    script_name=$(basename "${0}")
   	echo "${script_name}: ABORTING: HCP_RUN_UTILS environment variable must be set"
	exit 1
fi

my_path=$(dirname "${0}")
source ${HCP_RUN_UTILS}/shlib/utils.shlib
set_g_python_environment
source activate ${g_python_environment} 2>/dev/null
${my_path}/one_subject_completion_checker.py $@
source deactivate 2>/dev/null
