#!/bin/bash

if [ -z "${XNAT_PBS_JOBS}" ]; then
	script_name=$(basename "${0}")
	echo "${script_name}: ABORTING: XNAT_PBS_JOBS environment variable must be set"
	exit 1
fi

if [ -z "${HCP_RUN_UTILS}" ]; then
	echo "${g_script_name}: ABORTING: HCP_RUN_UTILS environment variable must be set"
	exit 1
fi

source ${HCP_RUN_UTILS}/shlib/utils.shlib
set_g_python_environment
source activate ${g_python_environment} 2>/dev/null
${XNAT_PBS_JOBS}/lib/ccf/structural_preprocessing/CheckStructuralPreprocessingPrereqsBatch.py $@
source deactivate 2>/dev/null
